# Site settings
title: "Azizkhon Ishankhonov"
description: "Azizkhon Ishankhonov Full Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"

resume_name:                    "Azizkhon Ishankhonov"
resume_title:                   "Full-stack Engineer"
resume_contact_email:           "azizxon_uz@hotmail.com"
resume_contact_telephone:       "+7 (968) 536-43-83"
resume_contact_address:         "Moscow, Russia"
resume_header_contact_info: "Moscwo, Russia | +7 (968) 536-43-83 | azizxon_uz@hotmail.com"
resume_header_intro: "<p>What is any ocean but a multitude of drops?</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_apprenticeship:  true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/azizxon/"
  resume_linkedin_url:          "https://www.linkedin.com/in/azizxon"
resume_print_social_links:      true

# Design settings
resume_theme:                   default